# Site settings
title: Raisa Velthuis' Code Repository
description: 'Code snippets related to my research'
url: 'http://www.raisavelthuis.com/'
/baseurl: '/velthuis'
profilepic: '/images/raisa.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: G-8YLFEXNM95
font_awesome: '71be032b81.js'

author:
  name: 'Raisa Velthuis'
  email: raisa.velthuis@villanova.edu
  twitter_username: raisaing
  github_username:  velthuis
  linkedin_username:  raisav
  ssrn_username: 2205100

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

