# Site settings
title: Raisa Velthuis' Code Repository
description: 'Assistant Professor of Finance at Villanova University'
url: 'http://www.raisavelthuis.com/'
/baseurl: ''
profilepic: '/images/raisa.jpg'
bkimage: '/images/amsterdam-bw.jpg'
google_analytics: G-8YLFEXNM95
font_awesome: '71be032b81.js' # set up a free account at fontawesome.com to get your ID

author:
  name: 'Raisa Velthuis'
  email: raisa.velthuis@villanova.edu
  twitter_username: raisaing
  github_username:  velthuis
  linkedin_username:  raisav
  ssrn_id: 2205100
  # scopus_id:
  # orcid_id: 
  # gscholar_username:

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

